### ISSUE TITLE
wrong agent

### ISSUE THREAD

**Issue by vansaw** [E1Bos/VALocker#1]
If every agent is not unlocked it locks the wrong agent

**Comment by vansaw** [comment]
nvm, i accidentally pressed all in agent toggle

**Comment by E1Bos** [comment]
Cheers, thanks for opening an issue, glad you managed to sort out the issue. Let me know if you're experiencing any other issues or bugs, I'm more than happy to expand functionality to ensure it runs on other people's systems.
