### ISSUE TITLE
[BUG] It wont lock on an agent

### ISSUE THREAD

**Issue by vansaw** [E1Bos/VALocker#13]
**Describe the bug**
It does not lock an agent nor change status when valorant, it only locks in when i manually change the status

![image_2024-12-08_202418042](https://github.com/user-attachments/assets/9e49346d-9a88-49db-87a3-e275ed9c3f85)

**Expected behavior**
It should lock in an agent then change valocker status after locking

**Program Information:**
 - Version 2.2.1

**Comment by E1Bos** [comment]
Thanks for bringing this up to my attention, I'll investigate the problem.

**Comment by E1Bos** [comment]
@vansaw I can't seem to replicate the issue on my end, it works both on windowed fullscreen/fullscreen and with the various modes.

Can you please confirm:
1. Your display resolution
2. If your framerate is capped/uncapped at some value
3. If you're using AMD Radeon Image Sharpening, Nvidia Freestyle, or any upscaling programs

**Comment by vansaw** [comment]
1.  1920x1080
2.  Uncapped
3. i dont think i have any upscaling programs.

**Comment by E1Bos** [comment]
Try capping your framerate to 120 or lower and see if that fixes the issue

**Comment by vansaw** [comment]
It fixed it, thanks

**Comment by E1Bos** [comment]
great, glad that worked!

**Comment by vansaw** [comment]
@E1Bos I started using the instalocker again but it is not clicking again, even with the fps cap at 120 during picking agent

it worked once but suddenly stopped working after
